### ISSUE TITLE
Compile error building (from fresh source) just now

### ISSUE THREAD

**Issue by analyticd** [commercial-emacs/commercial-emacs#332]
thread.c:755:16: error: implicit declaration of function 'ns_alloc_autorelease_pool' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  void *pool = ns_alloc_autorelease_pool ();
               ^
thread.c:755:9: warning: incompatible integer to pointer conversion initializing 'void *' with an expression of type 'int' [-Wint-conversion]
  void *pool = ns_alloc_autorelease_pool ();
        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thread.c:801:3: error: implicit declaration of function 'ns_release_autorelease_pool' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  ns_release_autorelease_pool (pool);
  ^
thread.c:801:3: note: did you mean 'ns_alloc_autorelease_pool'?
thread.c:755:16: note: 'ns_alloc_autorelease_pool' declared here
  void *pool = ns_alloc_autorelease_pool ();
               ^
1 warning and 2 errors generated.
make[1]: *** [thread.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [src] Error 2

**Comment by dickmao** [comment]
Word, thanks for letting me know.
