### ISSUE TITLE
Linking error on macos Catalina on Intel MBP

### ISSUE THREAD

**Issue by linearcombination** [commercial-emacs/commercial-emacs#333]
CC       lastfile.o
  CCLD     temacs
Undefined symbols for architecture x86_64:
  "_DGifSavedExtensionToGCB", referenced from:
      _gif_load in image.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [temacs] Error 1
make: *** [src] Error 2

**Comment by dickmao** [comment]
Verify gif_lib.h says GIFLIB_MAJOR >= 5.
Then verify `nm -D libgif.so | grep DGifSavedExtensionToGCB`
The file locations of the above might be beyond your ken.

**Comment by linearcombination** [comment]
More than one giflib on my system, so depends which one it is picking up. See later for details. However if it is picking up the one here:

>  ls /usr/local/Cellar/giflib/5.2.1/lib
 libgif.7.2.0.dylib
  libgif.7.dylib -> libgif.7.2.0.dylib
  libgif.a
  libgif.dylib -> libgif.7.dylib

Then
#define GIFLIB_MAJOR 5
#define GIFLIB_MINOR 2
#define GIFLIB_RELEASE 1

On MBP/macos/Intel we are dealing with .dylib and .a library files so the command should be:
> nm -g -C --defined-only libgif.dylib | grep DGifSavedExtensionToGCB
00000000000021ca T _DGifSavedExtensionToGCB

That being said, again, there is more than one giflib on my system due to various package dependencies and one of them is < 5:

❯ fd -t f gif_lib.h /
/System/Volumes/Data/Library/Frameworks/Mono.framework/Versions/6.10.0/include/gif_lib.h
/System/Volumes/Data/usr/local/Cellar/giflib/5.2.1/include/gif_lib.h
/System/Volumes/Data/opt/local/include/gif_lib.h
/System/Volumes/Data/opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/graphics/giflib/files/patch-gif_lib.h.diff
/opt/local/include/gif_lib.h
/opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/graphics/giflib/files/patch-gif_lib.h.diff
/usr/local/Cellar/giflib/5.2.1/include/gif_lib.h
/Library/Frameworks/Mono.framework/Versions/6.10.0/include/gif_lib.h

So maybe a configure switch could be passed to specify the version 5 giflib in your build? I briefly scanned your configure script to see such a switch I should use, but perhaps you could point me to it? Thanks.

**Comment by linearcombination** [comment]
Nevermind I see it in the INSTALL file --with-gif

**Comment by dickmao** [comment]
It's currently getting a recent .h (one with GIFLIB_MAJOR >= 5), but an
un-recent .dylib (one which doesn't define _DGifSavedExtensionToGCB).

CFLAGS governs the .h, and that presumably is good.

LDFLAGS governs the .dylib, and that presumably needs to be set like
"LDFLAGS=-L<the directory where libgif.dylib was shown to contain _DGifSavedExtensionToGCB.>"

Just as a template, this is what my incantations look like:

./autogen.sh
LDFLAGS=-L$HOME/.local/lib CFLAGS="-g3 -O2 -I$HOME/.local/include/" ./configure --prefix=$HOME/.local

**Comment by linearcombination** [comment]
Thanks @dickmao, that did it, it built successfully and I am using it. On the precipice of glory....
