### ISSUE TITLE
What happend to `pixel-scroll-precision-mode`?

### ISSUE THREAD

**Issue by Dickby** [commercial-emacs/commercial-emacs#371]

**Comment by dickmao** [comment]
I'm afraid that mode was too ugly to live.

In particular it foisted a brutal interface change to the primitive `window-text-pixel-size`.

Its mix-up of "scroll-up" versus "scroll-down", opposite to every other usage of up versus down in the codebase, was also objectionable.

I'm guessing the absence of this mode is a dealbreaker for Chinese emacs users.  Sorry we couldn't bring our nations together over this diplomatic incident.

**Comment by Dickby** [comment]
I don't know what other features had to give there lives for a lack of beauty,
but perhaps those things should be mentioned inside the `diverged code` section.
