### ISSUE TITLE
Tree-sitter instructions in error

### ISSUE THREAD

**Issue by mohammedzeglam-pg** [commercial-emacs/commercial-emacs#425]
sed -e 's|@LIBDIR@|/home/mzerone/.local/lib|;s|@INCLUDEDIR@|/home/mzerone/.local/include|;s|@VERSION@|0.6.3alpha5|' \
    -e 's|=/home/mzerone/.local|=${prefix}|' \
    -e 's|@PREFIX@|/home/mzerone/.local|' \
    tree-sitter.pc.in > '/home/mzerone/.local/lib/pkgconfig'/tree-sitter.pc
pkg-config --exact-version=0.6.3alpha5 tree-sitter
make: *** [Makefile:107: install-ci] Error 1
make: Leaving directory '/home/mzerone/open-source/commercial-emacs/tree-sitter'

**Comment by dickmao** [comment]
Install pkg-config.

**Comment by mohammedzeglam-pg** [comment]
> Install pkg-config.

it is installed and the problem in this line

    -e 's|@PREFIX@|/home/mzerone/.local|' \

**Comment by mohammedzeglam-pg** [comment]
i tried on mac m1 and manjaro both the same error

**Comment by dickmao** [comment]
You're right.  At least one crucial step is missing, that is, adding `/home/mzerone/.local/lib/pkgconfig/tree-sitter.pc` to your PKG_CONFIG_PATH environment variable.  There may be other steps missing.

I'd delete the `commercial-emacs/tree-sitter` directory, git pull `commercial-emacs/commercial-emacs`, and reattempt with the revised README.  Sorry.

**Comment by mohammedzeglam-pg** [comment]
Thanks an have a good day
