### ISSUE TITLE
Fail to build in Windows MSYS2 : 'O_CLOEXEC' undeclared

### ISSUE THREAD

**Issue by hxiong** [commercial-emacs/commercial-emacs#451]
Hi team, when trying to build latest commercial emacs in windows using MSYS2, I got  'O_CLOEXEC' undeclared  error after issuing 'make' command. 

`
make -C lib all
make[1]: Entering directory '/d/repos/commercial-emacs/lib'
  GEN      alloca.h
  GEN      byteswap.h
  GEN      errno.h
  GEN      execinfo.h
  GEN      getopt.h
  GEN      getopt-cdefs.h
  GEN      ieee754.h
  GEN      limits.h
  GEN      stdint.h
  GEN      string.h
  GEN      sys/random.h
  GEN      time.h
  CC       fingerprint.o
  CC       acl_entries.o
  CC       calloc.o
  CC       fopen.o
fopen.c: In function 'rpl_fopen':
fopen.c:126:27: error: 'O_CLOEXEC' undeclared (first use in this function)
  126 |             open_flags |= O_CLOEXEC;
      |                           ^~~~~~~~~
fopen.c:126:27: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:84: fopen.o] Error 1
make[1]: Leaving directory '/d/repos/commercial-emacs/lib'
make: *** [Makefile:456: lib] Error 2

`

The same error happened for GNU Emacs two years ago, but it's fixed then. No build error for latest GNU Emacs now in the same machine I use.

Could you provide some ideas on how to fix this?

Thanks.

**Comment by dickmao** [comment]
Thanks for you interest.  The [latest commit](https://github.com/commercial-emacs/commercial-emacs/actions/runs/2843497868) now builds across all platforms, but that's all it does.  My boastful claims have only ever been verified on a linux system.

**Comment by hxiong** [comment]
Thanks for looking into this. 
Pulling the latest commits on Aug 12th resolves the 'O_CLOEXEC' undeclared error. 
However, 'make' process triggers another 'sys_open' not declared error. 

In case others have similar errors, I manually changed 'lib/fopen.c' to only include '<stdio.h>', not '<config.h>' and then everything builds successfully.
Definitely not a fix, but it's a work-around to build it in my machine.

` /*
  #define _GL_ALREADY_INCLUDING_STDIO_H
  #include <config.h>

  /* Get the original definition of fopen.  It might be defined as a macro.  */
  #include <stdio.h>

  #undef _GL_ALREADY_INCLUDING_STDIO_H
  */
  #include <stdio.h>
`

This issue is resolved for me now. Please feel free to close. Thanks for the helping out.
