### ISSUE TITLE
Is there means (a variable or whatever) of distinguishing Commercial Emacs vs Regular Emacs

### ISSUE THREAD

**Issue by alecStewart1** [commercial-emacs/commercial-emacs#508]
Hello!

I would be interested in try Commercial Emacs out with my configuration (don't look at what's on my Github, it's not up-to-date), but in my config I *do* have some of the [tree-sitter packages](https://github.com/emacs-tree-sitter) and [flymake-collection](https://github.com/mohkale/flymake-collection) and with Commercial Emacs I probably wouldn't need those packages. *But* I don't want to get rid of sections my configurations entirely. Is there a `commercial-emacs-p` or something like `(featurep 'tree-sitter)` I could make use of?

**Comment by alecStewart1** [comment]
Ah, I found [this](https://github.com/commercial-emacs/commercial-emacs/blob/fc8ea354358b9ff895fe5b72f6c6697cc43bdbc0/lisp/progmodes/tree-sitter-prog-mode.el#L47). That might suffice.

**Comment by dickmao** [comment]
`(null (fboundp 'pixel-scroll-precision-mode))`

But joking aside, the goal is to be compatible with any existing configuration (well, modulo some atrocities like pixel-scroll-precision-mode).
